mqtt:
  enabled: true
  host: localhost
  port: 1883

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  ov:
    type: openvino
    device: AUTO
    model:
      path: /models/yolov8s.xml

# Optional: model modifications
model:
  width: 320
  height: 320
  input_tensor: nchw
  input_pixel_format: rgb
  model_type: yolov8
  labelmap_path: /models/coco.txt
  # Optional: Label name modifications. These are merged into the standard labelmap.
  labelmap:
    2: vehicle
    5: vehicle
    7: vehicle

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  width: 1920
  height: 1080
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  hwaccel_args: preset-vaapi

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  width: 1920
  height: 1080

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt
  track:
    - person
    # - vehicle
    # - cat
    # - dog
    # - bicycle
    # - motorcycle

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones:
      - zone_0
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days
      default: 90
      # Optional: Mode for retention.
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion

snapshots:
  # Optional: save a clean PNG copy of the snapshot image
  clean_copy: false
  # Optional: print a timestamp on the snapshots
  timestamp: true
  # Optional: draw bounding box on the snapshots
  bounding_box: true
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
    - zone_0
  retain:
    # Required: Default retention days
    default: 90

go2rtc:
  rtsp:
    username: "{FRIGATE_RTSP_USER}"
    password: "{FRIGATE_RTSP_PASSWORD}"
  streams:
    Cam-1:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<CAMERA_1_IP>/<RTSP_PATH>
    Cam-2:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@<CAMERA_2_IP>/<RTSP_PATH>

cameras:
  Cam-1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Cam-1 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
    zones:
      zone_0:
        coordinates: 1920,0,1920,1080,0,1080,0,0
  Cam-2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/Cam-2 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
    zones:
      zone_0:
        coordinates: 1920,0,1920,1080,0,1080,0,0
